bind_addr: 127.0.0.1:8099
log_config: "config/log.yml"
index:
  base_dir: test_index
  tokenizer:
    jieba:
      dict_path: "config/dict.txt"
      stop_word_path: "config/stop_word.txt"
  add:
    is_merge: true
    thread_num: 5
    buffer_size: 1000000000
